import Link from 'next/link';import {articles,guides} from '../data';import {Newsletter} from './interactive';import {KnowledgeTopics,LearningCards,WeeklyTip,DailyFact,MythFact,Discovery} from './learning-tools';import {HeroCarousel} from './hero-carousel';
const photo=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=85`;
function Card({item,href,kind='article'}:{item:any;href:string;kind?:string}){return <Link href={href} className="card"><div className="card-image" style={{backgroundImage:`url('${photo(item.image)}')`}}/><div className="card-body"><span className="eyebrow">{item.category||item.tag}</span><h3>{item.title}</h3><p className="meta">{kind==='article'?`${item.date} · ${item.read}`:item.price+' · PDF guide'}</p><span className="read-link">{kind==='article'?'READ ARTICLE':'EXPLORE GUIDE'}　↗</span></div></Link>}
export default function Home(){return <main>
<HeroCarousel/>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">A place to begin</span><h2>Popular health topics</h2></div><Link className="read-link" href="/hub">VISIT THE KNOWLEDGE HUB　→</Link></div><KnowledgeTopics/></div></section>
<section className="section soft"><div className="wrap"><WeeklyTip/></div></section>
<section className="section"><div className="wrap"><div className="featured-article"><div className="featured-image" style={{backgroundImage:`url('${photo(articles[0].image)}')`}}/><div className="featured-copy"><span className="eyebrow">FEATURED ARTICLE · {articles[0].category}</span><h2>{articles[0].title}</h2><p>{articles[0].excerpt}</p><p className="meta">{articles[0].date} · {articles[0].read}</p><Link className="btn" href={`/blog/${articles[0].slug}`}>Read Article　→</Link></div></div></div></section>
<section className="section soft"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Health explained simply</span><h2>Understand the basics</h2></div><Link className="read-link" href="/learn">ALL EXPLAINERS　→</Link></div><LearningCards limit={3}/></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">The latest</span><h2>From the journal</h2></div><Link className="read-link" href="/blog">VIEW ALL ARTICLES　→</Link></div><div className="cards">{articles.slice(1,4).map(a=><Card key={a.slug} item={a} href={`/blog/${a.slug}`}/>)}</div></div></section>
<section className="section"><div className="wrap"><DailyFact/></div></section>
<section className="section soft"><div className="wrap"><div className="section-head"><div><span className="eyebrow">A little clarity goes a long way</span><h2>Myth vs fact</h2></div></div><MythFact/></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Explore at your own pace</span><h2>The Health Knowledge Hub</h2></div><Link className="read-link" href="/hub">EXPLORE ALL TOPICS　→</Link></div><KnowledgeTopics/></div></section>
<section className="section soft"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Personalize your browsing</span><h2>What are you interested in?</h2></div></div><Discovery/></div></section>
<section className="section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">Practical knowledge, to keep</span><h2>Featured health guides</h2></div><Link className="read-link" href="/guides">BROWSE THE GUIDES　→</Link></div><div className="cards">{guides.map(g=><Card key={g.slug} item={g} href={`/guides/${g.slug}`} kind="guide"/>)}</div></div></section>
<section className="section" style={{paddingTop:0}}><div className="wrap resource"><div className="resource-pic" style={{backgroundImage:`url('${photo('photo-1455390582262-044cdead277a')}')`}}/><div className="resource-copy"><span className="eyebrow">A little something, on us</span><h2>Useful tools for real life.</h2><p>Try an educational quiz, browse plain-language definitions, or use our reflective checklist. Free learning for everyone—no purchase needed.</p><Link className="btn" href="/tools">Explore free learning tools　→</Link><p><Link className="read-link" href="/glossary">A–Z glossary</Link>　<Link className="read-link" href="/start-here">Learning paths</Link></p></div></div></section>
<section className="section soft"><div className="wrap" style={{maxWidth:760,textAlign:'center'}}><span className="eyebrow">Trust & transparency</span><h2 className="serif" style={{fontSize:40,fontWeight:500}}>Health information should feel human.</h2><p style={{color:'#555',lineHeight:1.9}}>We aim to explain health topics in clear, calm language, use reputable public references, and be transparent about what content is—and is not—medically reviewed. Our educational content supports, but never replaces, professional care.</p><Link href="/about" className="read-link">OUR EDITORIAL APPROACH　→</Link></div></section>
<section className="newsletter"><div className="wrap newsletter-in"><div><span className="eyebrow" style={{color:'#ef9691'}}>The Nurse Lizzy Health Letter</span><h2>Stay informed. Stay well.</h2><p>One useful health lesson every week. Email delivery is not connected yet; the form will be enabled when a provider is in place.</p></div><Newsletter/></div></section></main>}
